name: microcms-build
on: 
  push:
    branches: [main]
  repository_dispatch:
    types: [blog-update]
  schedule:
    # - cron: '0,15,30,45 * * * *'
    - cron:  "${{ vars.CRONTAB }}"
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        options:
          - テスト
          - 本番用ファイルをビルド
          - 本番サーバにビルドしたファイルをアップロード
        default: 'テスト'
        required: true
        description: '処理項目'


jobs:
  test:
    if: github.event.inputs.mode != '本番用ファイルをビルド' && github.event.inputs.mode != '本番サーバにビルドしたファイルをアップロード' && github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
    - run: echo 'test'
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        npm ci
        npx nuxi generate
      env:
        MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
        MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
    - run: |
        ls -l
        zip -r dist.zip dist
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ github.sha }}-${{ github.run_id }}
    #     path: dist.zip
    #     retention-days: 1

    # - uses: actions/download-artifact@v4
    # - run: |
    #     ls -la
  
  production_build:
    if: github.event.inputs.mode == '本番用ファイルをビルド' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo "production_build"

  production_deploy:
    if: github.event.inputs.mode == '本番サーバにビルドしたファイルをアップロード'  &&  github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "production_deploy"