name: microcms-build
on: 
  push:
    branches: [main]
  repository_dispatch:
    types: [blog-update]

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        npm ci
        npm run build
        npx nuxi generate
      env:
        MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
        MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
    - run: |
        cd .output/public
        ls -lR
        pwd
        zip -r public.zip .
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}-${{ github.run_id }}
        path: /home/runner/work/microcms-blog/microcms-blog/.output/public/public.zip
        retention-days: 1
    - run: sleep 30
         


